### ISSUE TITLE
多行省略展开收起，不满多行正常展示

### ISSUE THREAD

**Issue by hyhajnal** [hyhajnal/blog#6]
多行省略比较简单，直接用css属性 `line-clamp` 即可

``` html
<div class="item-body-reply" v-if="data.explain">
        <p class="item-body-explain" :class="{'reply-noexpend': !replyExpend}" :id="'reply-' + data.rateId">
          <strong>回复：</strong><span>{{data.explain}}</span>
        </p>
        <p class="reply-icon" @click="replyExpend = !replyExpend" v-if="showExpand">
          {{!replyExpend ? '展开' : '收起'}}
          <i :class="'icon-arrow-' + (replyExpend ? 'up' : 'down') "></i>
        </p>
</div>
```

``` css
.reply-noexpend {
    overflow : hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```

但是当内容少于行数时，需要隐藏展开收起按钮，就得借助 js了
同样加了 `line-clamp` ，什么时候这个p元素，超出省略了呢？
观察了两个元素，发现被省略的元素：`el.scrollHeight > el.offsetHeight`

``` js
initExpand() {
      this.$nextTick(() => {
        const el = document.getElementById(`reply-${this.data.rateId}`);
        if (el && (el.scrollHeight > el.offsetHeight)) {
          this.showExpand = true
        }
      })
}
```
